version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=admin_pw
      - POSTGRES_DB=pic_up

  localstack:
    image: localstack/localstack:2.1
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=local-access
      - AWS_SECRET_ACCESS_KEY=local-secret
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - ./.localstack/aws:/docker-entrypoint-initaws.d
